### ISSUE TITLE
Popup, Modal 컴포넌트 스크롤과 관련된 UI 버그 및 구조 수정

### ISSUE THREAD

**Issue by JaeHyunGround** [codeit5-Team8/torip-frontend#69]
## 어떤 버그인가요?

> 버그에 대해 알려주세요

1. 페이지에 스크롤이 존재할 때, 스크롤을 움직인 상태에서 Popup, Modal을 열면 `UI가 이상해지는 버그` 가 있습니다.
    - 뒷 배경인 어두운 배경이 짤려서 나오는 경우
    - Popup, Modal이 화면 중앙으로 오지 않는 경우

2. Popup, Modal을 닫으면 `스크롤이 유지되지 않고 최상단으로 이동하는 버그`가 있습니다.

개발 단계에서 스크롤이 존재할 때 환경을 제대로 고려하지 못한 것 같습니다. 
기능에는 큰 문제가 없어 보이나, 기능에도 문제가 발생한다면 추가 이슈 생성하겠습니다.

3. useModal, usePopup hook을 제거합니다.
    - 상태 관리 개념에 대해 착각하고 있던 부분이 있어 store에 state를 수정할 수 있는 hook을 만들었었는데, 상태 관리의 개념이 `현재 상태를 저장하고, 불러오는 것` 뿐만 아닌 `상태를 업데이트 하는 것` 도 포함되기에 store에 직접 접근하여 state를 수정하는 것은 당연한 것이었습니다....!!! (저장한다 에 너무 꽃혀있었던 같습니다..ㅠ)

## 어떤 상황에서 겪으셨나요?

> 버그를 겪으신 상황을 알려주세요

스크롤이 존재하는 페이지에서 Popup, Modal을 열고 닫을 때

## 참고할만한 자료가 있을까요?

> 참고 자료가 있다면 첨부해 주세요

**Comment by SSUK-H** [comment]
기존 위치를 저장하고 hidden 처리하거나 [link 활용](https://velog.io/@jihwan1211/Next.js-%EB%AA%A8%EB%8B%AC-%EB%92%B7%EB%B0%B0%EA%B2%BD-%EC%8A%A4%ED%81%AC%EB%A1%A4-%EC%9C%84%EC%B9%98-%EC%9C%A0%EC%A7%80%ED%95%98%EA%B8%B0-intercepting-Routes-parallel-Routes) 이 방법은 어떨까요..?
